=== hmrc/individuals-employments-income-api/resources/public/api/conf/1.0/schemas/employments_financial_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve an Employment and its Financial Details Response",
  "description": "Retrieve an Employment and its Financial Details Response",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "employments_financial_definitions.json#/definitions/submittedOn"},
    "source": {"$ref": "employments_financial_definitions.json#/definitions/source"},
    "customerAdded": {"$ref": "employments_financial_definitions.json#/definitions/customerAdded"},
    "dateIgnored": {"$ref": "employments_financial_definitions.json#/definitions/dateIgnored"},
    "employment": {"$ref": "employments_financial_definitions.json#/definitions/retrieveEmployment"},
    "links": {"$ref": "employments_financial_definitions.json#/definitions/links"}
  },
  "required": ["submittedOn", "employment"]
}

=== hmrc/individuals-employments-income-api/resources/public/api/conf/1.0/examples/employments/financialDetails/retrieve_hmrc_response.json
{
  "submittedOn": "2020-01-04T05:01:01.000Z",
  "dateIgnored": "2020-03-05T05:01:01.000Z",
  "employment": {
    "employmentSequenceNumber": "1002",
    "payrollId": "123456789999",
    "companyDirector": false,
    "closeCompany": true,
    "directorshipCeasedDate": "2020-02-12",
    "startDate": "2019-04-21",
    "cessationDate": "2020-03-11",
    "occupationalPension": false,
    "disguisedRemuneration": false,
    "employer": {
      "employerRef": "223/AB12399",
      "employerName": "Employer Name Ltd."
    },
    "pay": {
      "taxablePayToDate": 34234.15,
      "totalTaxToDate": 6782.92,
      "payFrequency": "CALENDAR MONTHLY",
      "paymentDate": "2020-04-23",
      "taxWeekNo": 32,
      "taxMonthNo": 8
    },
    "customerEstimatedPay": {
      "amount": 1500.99
    },
    "deductions": {
      "studentLoans": {
        "uglDeductionAmount": 13343.45,
        "pglDeductionAmount": 24242.56
      }
    },
    "benefitsInKind": {
      "accommodation": 455.67,
      "assets": 435.54,
      "assetTransfer": 24.58,
      "beneficialLoan": 33.89,
      "car": 3434.78,
      "carFuel": 34.56,
      "educationalServices": 445.67,
      "entertaining": 434.45,
      "expenses": 3444.32,
      "medicalInsurance": 4542.47,
      "telephone": 243.43,
      "service": 45.67,
      "taxableExpenses": 24.56,
      "van": 56.29,
      "vanFuel": 14.56,
      "mileage": 34.23,
      "nonQualifyingRelocationExpenses": 54.62,
      "nurseryPlaces": 84.29,
      "otherItems": 67.67,
      "paymentsOnEmployeesBehalf": 67.23,
      "personalIncidentalExpenses": 74.29,
      "qualifyingRelocationExpenses": 78.24,
      "employerProvidedProfessionalSubscriptions": 84.56,
      "employerProvidedServices": 56.34,
      "incomeTaxPaidByDirector": 67.34,
      "travelAndSubsistence": 56.89,
      "vouchersAndCreditCards": 34.90,
      "nonCash": 23.89
    }
  },
  "links": [
    {
      "href":"/individuals/income-received/employments/TC663795B/2021-22/4557ecb5-fd32-48cc-81f5-e6acd1099f3c/financial-details",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/income-received/employments/TC663795B/2021-22/4557ecb5-fd32-48cc-81f5-e6acd1099f3c/financial-details",
      "rel":"create-and-amend-employment-financial-details",
      "method":"PUT"
    },
    {
      "href":"/individuals/income-received/employments/TC663795B/2021-22/4557ecb5-fd32-48cc-81f5-e6acd1099f3c/financial-details",
      "rel":"delete-employment-financial-details",
      "method":"DELETE"
    }
  ]
}
