=== hmrc/individuals-employments-income-api/resources/public/api/conf/1.0/schemas/otherEmployment_amend_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Create And Amend Other Employment Income Request",
  "description": "Create And Amend Other Employment Income Request",
  "type": "object",
  "properties": {
    "shareOption": {"$ref": "otherEmployment_definitions.json#/definitions/shareOption"},
    "sharesAwardedOrReceived": {"$ref": "otherEmployment_definitions.json#/definitions/sharesAwardedOrReceived"},
    "disability": {"$ref": "otherEmployment_definitions.json#/definitions/disability"},
    "foreignService": {"$ref": "otherEmployment_definitions.json#/definitions/foreignService"},
    "lumpSums": {"$ref": "otherEmployment_definitions.json#/definitions/lumpSums"}
  }
}

=== hmrc/individuals-employments-income-api/resources/public/api/conf/1.0/examples/otherEmploymentIncome/amend_request.json
{
  "shareOption":[
    {
      "employerName":"Company Ltd",
      "employerRef":"123/AB456",
      "schemePlanType":"EMI",
      "dateOfOptionGrant":"2019-11-20",
      "dateOfEvent":"2019-11-20",
      "optionNotExercisedButConsiderationReceived":true,
      "amountOfConsiderationReceived":23122.22,
      "noOfSharesAcquired":1,
      "classOfSharesAcquired":"FIRST",
      "exercisePrice":12.22,
      "amountPaidForOption":123.22,
      "marketValueOfSharesOnExcise":1232.22,
      "profitOnOptionExercised":1232.33,
      "employersNicPaid":2312.22,
      "taxableAmount":2132.22
    }
  ],
  "sharesAwardedOrReceived":[
    {
      "employerName":"Company Ltd",
      "employerRef":"123/AB456",
      "schemePlanType":"SIP",
      "dateSharesCeasedToBeSubjectToPlan":"2019-11-10",
      "noOfShareSecuritiesAwarded":11,
      "classOfShareAwarded":"FIRST",
      "dateSharesAwarded":"2019-11-20",
      "sharesSubjectToRestrictions":true,
      "electionEnteredIgnoreRestrictions":false,
      "actualMarketValueOfSharesOnAward":2123.22,
      "unrestrictedMarketValueOfSharesOnAward":123.22,
      "amountPaidForSharesOnAward":123.22,
      "marketValueAfterRestrictionsLifted":1232.22,
      "taxableAmount":12321.22
    }
  ],
  "disability":{
    "customerReference":"EMP123A",
    "amountDeducted":1223.22
  },
  "foreignService":{
    "customerReference":"EMP123A",
    "amountDeducted":1223.22
  },
  "lumpSums": [
    {
      "employerName":"Company Ltd",
      "employerRef":"123/AB456",
      "taxableLumpSumsAndCertainIncome": {
        "amount": 5000.99,
        "taxPaid": 5000.99,
        "taxTakenOffInEmployment": false
      },
      "benefitFromEmployerFinancedRetirementScheme": {
        "amount": 5000.99,
        "exemptAmount": 5000.99,
        "taxPaid": 500.99,
        "taxTakenOffInEmployment": false
      },
      "redundancyCompensationPaymentsOverExemption": {
        "amount": 4000.99,
        "taxPaid": 400.99,
        "taxTakenOffInEmployment": false
      },
      "redundancyCompensationPaymentsUnderExemption": {
        "amount": 5000.99
      }
    }
  ]
}
